<a href="https://colab.research.google.com/github/haneesha-thasni/gapminder-data-graphs/blob/main/gapminder_data_graphs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
path="/content/gapminder_data_graphs.csv"

In [ ]:
df=pd.read_csv(path)

In [ ]:
df

,country,continent,year,life_exp,hdi_index,co2_consump,gdp,services
0,Afghanistan,Asia,1998,53.3,0.344,0.0522,NaN,24.4
1,Afghanistan,Asia,1999,54.7,0.348,0.0402,NaN,24.6
2,Afghanistan,Asia,2000,54.7,0.350,0.0370,NaN,24.7
3,Afghanistan,Asia,2001,54.8,0.353,0.0376,NaN,24.7
4,Afghanistan,Asia,2002,55.5,0.384,0.0471,333.0,25.6
...,...,...,...,...,...,...,...,...
3670,Zimbabwe,Africa,2014,58.0,0.547,0.8810,1440.0,25.4
3671,Zimbabwe,Africa,2015,58.6,0.553,0.8810,1450.0,25.7
3672,Zimbabwe,Africa,2016,59.2,0.558,0.7710,1430.0,26.1
3673,Zimbabwe,Africa,2017,59.9,0.563,0.8450,1480.0,26.6
3674,Zimbabwe,Africa,2018,60.6,0.569,0.8500,1510.0,27.2

In [ ]:
df.shape
# retreive the shape of dataset

(3675, 8)

In [ ]:
df.info()
# to retreive the information about the dataset
# information like
''' class, index range, total number of columns, column names, data type, memory usage, null value count, non null-value count'''

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3675 entries, 0 to 3674
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   country      3675 non-null   object
 1   continent    3675 non-null   object
 2   year         3675 non-null   int64
 3   life_exp     3675 non-null   float64
 4   hdi_index    3563 non-null   float64
 5   co2_consump  3671 non-null   float64
 6   gdp          3633 non-null   float64
 7   services     3675 non-null   float64
dtypes: float64(5), int64(1), object(2)
memory usage: 229.8+ KB

' class, index range, total number of columns, column names, data type, memory usage, null value count, non null-value count'

In [ ]:
df.describe()
# get description of dataset

,year,life_exp,hdi_index,co2_consump,gdp,services
count,3675.000000,3675.000000,3563.000000,3671.000000,3633.000000,3675.000000
mean,2008.000000,69.849306,0.674864,4.712731,11966.053675,51.248705
std,6.056125,8.886563,0.164834,6.567435,17105.787953,18.312501
min,1998.000000,32.500000,0.255000,0.015900,238.000000,5.590000
25%,2003.000000,63.900000,0.537500,0.560500,1470.000000,37.600000
50%,2008.000000,71.700000,0.699000,2.250000,4280.000000,52.900000
75%,2013.000000,76.400000,0.805000,6.615000,13600.000000,65.700000
max,2018.000000,84.800000,0.956000,67.100000,105000.000000,88.500000

In [ ]:
df.describe(include='all')
# used to describe all columns in a dataset

,country,continent,year,life_exp,hdi_index,co2_consump,gdp,services
count,3675,3675,3675.000000,3675.000000,3563.000000,3671.000000,3633.000000,3675.000000
unique,175,6,NaN,NaN,NaN,NaN,NaN,NaN
top,Afghanistan,Africa,NaN,NaN,NaN,NaN,NaN,NaN
freq,21,1071,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,2008.000000,69.849306,0.674864,4.712731,11966.053675,51.248705
std,NaN,NaN,6.056125,8.886563,0.164834,6.567435,17105.787953,18.312501
min,NaN,NaN,1998.000000,32.500000,0.255000,0.015900,238.000000,5.590000
25%,NaN,NaN,2003.000000,63.900000,0.537500,0.560500,1470.000000,37.600000
50%,NaN,NaN,2008.000000,71.700000,0.699000,2.250000,4280.000000,52.900000
75%,NaN,NaN,2013.000000,76.400000,0.805000,6.615000,13600.000000,65.700000
max,NaN,NaN,2018.000000,84.800000,0.956000,67.100000,105000.000000,88.500000

In [ ]:
df.ndim
# ndim used to idendify whether data is which dimension

2

In [ ]:
df.columns
# to retreive the column names

Index(['country', 'continent', 'year', 'life_exp', 'hdi_index', 'co2_consump',
       'gdp', 'services'],
      dtype='object')

In [ ]:
df['country']
# to retreive the specified column, which is one dimension
# method 1

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...
3670       Zimbabwe
3671       Zimbabwe
3672       Zimbabwe
3673       Zimbabwe
3674       Zimbabwe
Name: country, Length: 3675, dtype: object

In [ ]:
df.country
# to retreive the specified column, one dimension
# method 2

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...
3670       Zimbabwe
3671       Zimbabwe
3672       Zimbabwe
3673       Zimbabwe
3674       Zimbabwe
Name: country, Length: 3675, dtype: object

In [ ]:
df[['country','continent']]
# to retreive columns, which is two dimension

          country continent
0     Afghanistan      Asia
1     Afghanistan      Asia
2     Afghanistan      Asia
3     Afghanistan      Asia
4     Afghanistan      Asia
...           ...       ...
3670     Zimbabwe    Africa
3671     Zimbabwe    Africa
3672     Zimbabwe    Africa
3673     Zimbabwe    Africa
3674     Zimbabwe    Africa

[3675 rows x 2 columns]

In [ ]:
data=df[['country','continent']]
# store to a variable

In [ ]:
data
#  call the variable to print specified data

          country continent
0     Afghanistan      Asia
1     Afghanistan      Asia
2     Afghanistan      Asia
3     Afghanistan      Asia
4     Afghanistan      Asia
...           ...       ...
3670     Zimbabwe    Africa
3671     Zimbabwe    Africa
3672     Zimbabwe    Africa
3673     Zimbabwe    Africa
3674     Zimbabwe    Africa

[3675 rows x 2 columns]

In [ ]:
df.nunique()
# to get number of unique values in a dataset

country         175
continent         6
year             21
life_exp        396
hdi_index       652
co2_consump    1707
gdp            1593
services        742
dtype: int64

In [ ]:
df['country'].unique()
# to get unique items in a specified column

array(['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
       'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas',
       'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium',
       'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina',
       'Botswana', 'Brazil', 'Brunei', 'Bulgaria', 'Burkina Faso',
       'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde',
       'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia',
       'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.', 'Costa Rica',
       "Cote d'Ivoire", 'Croatia', 'Cuba', 'Cyprus', 'Czech Republic',
       'Denmark', 'Djibouti', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Estonia', 'Eswatini',
       'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon', 'Gambia',
       'Georgia', 'Germany', 'Ghana', 'Greece', 'Guatemala', 'Guinea',
       'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hong Kong, China',
       'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq',
       'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan',
       'Kazakhstan', 'Kenya', 'Kuwait', 'Kyrgyz Republic', 'Lao',
       'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Lithuania',
       'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives',
       'Mali', 'Malta', 'Mauritania', 'Mauritius', 'Mexico', 'Moldova',
       'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar',
       'Namibia', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua',
       'Niger', 'Nigeria', 'North Macedonia', 'Norway', 'Oman',
       'Pakistan', 'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay',
       'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar', 'Romania',
       'Russia', 'Rwanda', 'Samoa', 'Sao Tome and Principe',
       'Saudi Arabia', 'Senegal', 'Serbia', 'Sierra Leone', 'Singapore',
       'Slovak Republic', 'Slovenia', 'Solomon Islands', 'South Africa',
       'South Korea', 'South Sudan', 'Spain', 'Sri Lanka', 'St. Lucia',
       'St. Vincent and the Grenadines', 'Sudan', 'Suriname', 'Sweden',
       'Switzerland', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste',
       'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey',
       'Turkmenistan', 'Uganda', 'Ukraine', 'United Arab Emirates',
       'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan',
       'Vanuatu', 'Vietnam', 'Yemen', 'Zambia', 'Zimbabwe'], dtype=object)

In [ ]:
df[(df['country']=='Afghanistan')]

,country,continent,year,life_exp,hdi_index,co2_consump,gdp,services
0,Afghanistan,Asia,1998,53.3,0.344,0.0522,NaN,24.4
1,Afghanistan,Asia,1999,54.7,0.348,0.0402,NaN,24.6
2,Afghanistan,Asia,2000,54.7,0.350,0.0370,NaN,24.7
3,Afghanistan,Asia,2001,54.8,0.353,0.0376,NaN,24.7
4,Afghanistan,Asia,2002,55.5,0.384,0.0471,333.0,25.6
5,Afghanistan,Asia,2003,56.5,0.393,0.0509,346.0,25.9
6,Afghanistan,Asia,2004,57.1,0.409,0.0368,336.0,26.1
7,Afghanistan,Asia,2005,57.6,0.418,0.0515,360.0,26.5
8,Afghanistan,Asia,2006,58.0,0.429,0.0622,368.0,26.9
9,Afghanistan,Asia,2007,58.5,0.447,0.0838,409.0,27.7
10,Afghanistan,Asia,2008,59.2,0.447,0.1520,415.0,28.2
11,Afghanistan,Asia,2009,59.9,0.460,0.2380,492.0,29.5
12,Afghanistan,Asia,2010,60.5,0.472,0.2900,547.0,30.7
13,Afghanistan,Asia,2011,61.0,0.477,0.4060,533.0,31.7
14,Afghanistan,Asia,2012,61.4,0.489,0.3450,580.0,32.8
15,Afghanistan,Asia,2013,61.9,0.496,0.2800,592.0,33.8
16,Afghanistan,Asia,2014,61.9,0.500,0.2530,588.0,34.8
17,Afghanistan,Asia,2015,61.9,0.500,0.2620,578.0,35.8
18,Afghanistan,Asia,2016,62.0,0.502,0.2450,575.0,36.9
19,Afghanistan,Asia,2017,62.9,0.506,0.2470,576.0,38.0
20,Afghanistan,Asia,2018,62.7,0.509,0.2540,569.0,38.4

In [ ]:
df[(df['country']=='Argentina')&(df['year']>=2000)]

,country,continent,year,life_exp,hdi_index,co2_consump,gdp,services
86,Argentina,South America,2000,74.2,0.781,3.85,10700.0,76.6
87,Argentina,South America,2001,74.3,0.786,3.58,10100.0,77.2
88,Argentina,South America,2002,74.3,0.781,3.30,8940.0,78.8
89,Argentina,South America,2003,74.4,0.786,3.54,9630.0,76.8
90,Argentina,South America,2004,74.9,0.787,4.08,10400.0,75.8
91,Argentina,South America,2005,75.3,0.788,4.15,11200.0,75.5
92,Argentina,South America,2006,75.4,0.812,4.45,12000.0,75.3
93,Argentina,South America,2007,75.3,0.817,4.39,12900.0,75.0
94,Argentina,South America,2008,75.7,0.821,4.70,13300.0,74.8
95,Argentina,South America,2009,75.8,0.821,4.42,12400.0,75.6
96,Argentina,South America,2010,75.9,0.829,4.57,13600.0,75.4
97,Argentina,South America,2011,76.0,0.835,4.61,14200.0,75.4
98,Argentina,South America,2012,76.2,0.834,4.60,13900.0,75.7
99,Argentina,South America,2013,76.3,0.835,4.56,14100.0,75.4
100,Argentina,South America,2014,76.5,0.836,4.56,13600.0,75.3
101,Argentina,South America,2015,76.5,0.840,4.64,13800.0,76.1
102,Argentina,South America,2016,76.2,0.839,4.60,13400.0,77.0
103,Argentina,South America,2017,76.3,0.843,4.55,13600.0,77.5
104,Argentina,South America,2018,76.5,0.842,4.41,13100.0,78.0

In [ ]:
df.isnull().sum()
# get null value items
# method 1

country          0
continent        0
year             0
life_exp         0
hdi_index      112
co2_consump      4
gdp             42
services         0
dtype: int64

In [ ]:
df.isna().sum()
# using this method to get null values
# method 2

country          0
continent        0
year             0
life_exp         0
hdi_index      112
co2_consump      4
gdp             42
services         0
dtype: int64

In [ ]:
df['country'].value_counts()
# to retreive the counts of value occured in a specified column

country
Afghanistan    21
Palestine      21
New Zealand    21
Nicaragua      21
Niger          21
               ..
Germany        21
Ghana          21
Greece         21
Guatemala      21
Zimbabwe       21
Name: count, Length: 175, dtype: int64

In [ ]:
df.value_counts()
# to retreive the counts of value in a dataset

country          continent  year  life_exp  hdi_index  co2_consump  gdp     services
Afghanistan      Asia       2002  55.5      0.384      0.0471       333.0   25.6        1
North Macedonia  Europe     2000  71.5      0.677      5.9300       3270.0  40.7        1
Nigeria          Africa     2008  58.5      0.484      0.6310       2170.0  46.4        1
                            2009  59.0      0.490      0.4860       2290.0  47.4        1
                            2010  59.6      0.482      0.7130       2400.0  48.4        1
                                                                                       ..
Gambia           Africa     2003  61.8      0.422      0.2070       724.0   48.6        1
                            2004  62.0      0.431      0.2160       751.0   49.4        1
                            2005  62.2      0.435      0.2110       711.0   49.6        1
                            2006  62.4      0.440      0.2210       686.0   49.9        1
Zimbabwe         Africa     2018  60.6      0.569      0.8500       1510.0  27.2        1
Name: count, Length: 3532, dtype: int64

In [ ]:
df.loc[:,['country','continent','year','life_exp']]
# to  get some condition using loc method
# " : " denotes full data
# [] - '' specifing columns

          country continent  year  life_exp
0     Afghanistan      Asia  1998      53.3
1     Afghanistan      Asia  1999      54.7
2     Afghanistan      Asia  2000      54.7
3     Afghanistan      Asia  2001      54.8
4     Afghanistan      Asia  2002      55.5
...           ...       ...   ...       ...
3670     Zimbabwe    Africa  2014      58.0
3671     Zimbabwe    Africa  2015      58.6
3672     Zimbabwe    Africa  2016      59.2
3673     Zimbabwe    Africa  2017      59.9
3674     Zimbabwe    Africa  2018      60.6

[3675 rows x 4 columns]

In [ ]:
df.loc[:,'country':'life_exp']
# using this methd to print full data in column country to life_exp

          country continent  year  life_exp
0     Afghanistan      Asia  1998      53.3
1     Afghanistan      Asia  1999      54.7
2     Afghanistan      Asia  2000      54.7
3     Afghanistan      Asia  2001      54.8
4     Afghanistan      Asia  2002      55.5
...           ...       ...   ...       ...
3670     Zimbabwe    Africa  2014      58.0
3671     Zimbabwe    Africa  2015      58.6
3672     Zimbabwe    Africa  2016      59.2
3673     Zimbabwe    Africa  2017      59.9
3674     Zimbabwe    Africa  2018      60.6

[3675 rows x 4 columns]

In [ ]:
df.dtypes
# to retrieve data types of a dataset

country         object
continent       object
year             int64
life_exp       float64
hdi_index      float64
co2_consump    float64
gdp            float64
services       float64
dtype: object

In [ ]:
df.select_dtypes('object')
# to retreive items in  selected one datatype

          country continent
0     Afghanistan      Asia
1     Afghanistan      Asia
2     Afghanistan      Asia
3     Afghanistan      Asia
4     Afghanistan      Asia
...           ...       ...
3670     Zimbabwe    Africa
3671     Zimbabwe    Africa
3672     Zimbabwe    Africa
3673     Zimbabwe    Africa
3674     Zimbabwe    Africa

[3675 rows x 2 columns]

In [ ]:
df.select_dtypes(['object','int64'])
# to retrieve items in selected two or more data types

          country continent  year
0     Afghanistan      Asia  1998
1     Afghanistan      Asia  1999
2     Afghanistan      Asia  2000
3     Afghanistan      Asia  2001
4     Afghanistan      Asia  2002
...           ...       ...   ...
3670     Zimbabwe    Africa  2014
3671     Zimbabwe    Africa  2015
3672     Zimbabwe    Africa  2016
3673     Zimbabwe    Africa  2017
3674     Zimbabwe    Africa  2018

[3675 rows x 3 columns]

In [ ]:
df.loc[0:10,'year':]
# get data 0 to 10 row and column year upto

    year  life_exp  hdi_index  co2_consump    gdp  services
0   1998      53.3      0.344       0.0522    NaN      24.4
1   1999      54.7      0.348       0.0402    NaN      24.6
2   2000      54.7      0.350       0.0370    NaN      24.7
3   2001      54.8      0.353       0.0376    NaN      24.7
4   2002      55.5      0.384       0.0471  333.0      25.6
5   2003      56.5      0.393       0.0509  346.0      25.9
6   2004      57.1      0.409       0.0368  336.0      26.1
7   2005      57.6      0.418       0.0515  360.0      26.5
8   2006      58.0      0.429       0.0622  368.0      26.9
9   2007      58.5      0.447       0.0838  409.0      27.7
10  2008      59.2      0.447       0.1520  415.0      28.2

In [ ]:
df.loc[3600:,:]
# to get data from 3600 upto and full columns

,country,continent,year,life_exp,hdi_index,co2_consump,gdp,services
3600,Vietnam,Asia,2007,72.9,0.640,1.180,1430.0,30.3
3601,Vietnam,Asia,2008,73.0,0.647,1.310,1500.0,30.4
3602,Vietnam,Asia,2009,73.1,0.659,1.410,1560.0,30.6
3603,Vietnam,Asia,2010,73.2,0.661,1.550,1650.0,29.6
3604,Vietnam,Asia,2011,73.3,0.671,1.630,1730.0,30.4
...,...,...,...,...,...,...,...,...
3670,Zimbabwe,Africa,2014,58.0,0.547,0.881,1440.0,25.4
3671,Zimbabwe,Africa,2015,58.6,0.553,0.881,1450.0,25.7
3672,Zimbabwe,Africa,2016,59.2,0.558,0.771,1430.0,26.1
3673,Zimbabwe,Africa,2017,59.9,0.563,0.845,1480.0,26.6
3674,Zimbabwe,Africa,2018,60.6,0.569,0.850,1510.0,27.2

### **iloc method**

In [ ]:
df.iloc[0:5,0:4]
# to get data from 0 index to 5 and column 0 to life_exp
# in this case life_exp is 3rd position, but to retreive this add one position

       country continent  year  life_exp
0  Afghanistan      Asia  1998      53.3
1  Afghanistan      Asia  1999      54.7
2  Afghanistan      Asia  2000      54.7
3  Afghanistan      Asia  2001      54.8
4  Afghanistan      Asia  2002      55.5

In [ ]:
df.iloc[:,2:]
# to get data from full row and column year upto

      year  life_exp  hdi_index  co2_consump     gdp  services
0     1998      53.3      0.344       0.0522     NaN      24.4
1     1999      54.7      0.348       0.0402     NaN      24.6
2     2000      54.7      0.350       0.0370     NaN      24.7
3     2001      54.8      0.353       0.0376     NaN      24.7
4     2002      55.5      0.384       0.0471   333.0      25.6
...    ...       ...        ...          ...     ...       ...
3670  2014      58.0      0.547       0.8810  1440.0      25.4
3671  2015      58.6      0.553       0.8810  1450.0      25.7
3672  2016      59.2      0.558       0.7710  1430.0      26.1
3673  2017      59.9      0.563       0.8450  1480.0      26.6
3674  2018      60.6      0.569       0.8500  1510.0      27.2

[3675 rows x 6 columns]

In [ ]:
data=df.copy()
# to take a copy of dataset
# this is important in data analytics
#  using copy dataset to any applications because one column will be add and remove will not effect the original dataset.
# store in a different variable name

In [ ]:
data
# call the copied data set

,country,continent,year,life_exp,hdi_index,co2_consump,gdp,services
0,Afghanistan,Asia,1998,53.3,0.344,0.0522,NaN,24.4
1,Afghanistan,Asia,1999,54.7,0.348,0.0402,NaN,24.6
2,Afghanistan,Asia,2000,54.7,0.350,0.0370,NaN,24.7
3,Afghanistan,Asia,2001,54.8,0.353,0.0376,NaN,24.7
4,Afghanistan,Asia,2002,55.5,0.384,0.0471,333.0,25.6
...,...,...,...,...,...,...,...,...
3670,Zimbabwe,Africa,2014,58.0,0.547,0.8810,1440.0,25.4
3671,Zimbabwe,Africa,2015,58.6,0.553,0.8810,1450.0,25.7
3672,Zimbabwe,Africa,2016,59.2,0.558,0.7710,1430.0,26.1
3673,Zimbabwe,Africa,2017,59.9,0.563,0.8450,1480.0,26.6
3674,Zimbabwe,Africa,2018,60.6,0.569,0.8500,1510.0,27.2